version: '3.8'

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  frontend:
    image: sit32/smmw:frontend
    container_name: frontend
    volumes:
      - /opt/sm_deploy/www_frontend:/usr/share/nginx/html

    networks:
      - app-network

    ports:
      - "80:80"
      - "443:443"
    restart: always

  mysql:
    image: sit32/smmw:db
    container_name: mysql
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ghthhdh75hkiuygfh3g6k0
      - MYSQL_DATABASE=DB_SMMWEBSITE
      - MYSQL_USER=smmuser
      - MYSQL_PASSWORD=ndi8kkJ^#buBZ*nrd7s86CW3
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
    volumes:
      - /opt/mariadb:/var/lib/mysql

    networks:
      app-network:
        ipv4_address: 172.20.0.10

  backend:
    image: sit32/smmw:backend
    container_name: backend
    restart: on-failure
    depends_on:
      - mysql
      - redis
    volumes:
      - /opt/media_backend:/usr/src/app/media
    ports:
      - "8000:5005"
    networks:
      - app-network
    command: uwsgi  --http 0.0.0.0:5005 --uid www-data --ini uwsgi/sm.ini

  redis:
    image: redis:7.2-rc-alpine3.17
    container_name: redis
    restart: always
    # ports:
      # - '207.180.252.153:6379:6379'
    command: redis-server --save 20 1 --maxmemory 512mb --loglevel warning 
    # sysctls:
      # - vm.overcommit_memory = 1
      # - net.core.somaxconn = 4096
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

    networks:
      - app-network

volumes:
  cache:
    driver: local
