version: '3.8'

services:
  # postgres_db:
  # qDrant
  
  n8n:    
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      # - N8N_PROTOCOL=https
      # - N8N_SSL_KEY=/etc/ssl/private/ssl.key
      # - N8N_SSL_CERT=/etc/ssl/certs/ssl.cert

      # - TZ=America/USA
      # - N8N_BASIC_AUTH_ACTIVE=true
      # - N8N_BASIC_AUTH_USER=n8n_user
      # - N8N_BASIC_AUTH_PASSWORD=UJkhbyfuo231

    volumes:
      - n8n_data:/home/node/.n8n
      # - ./certs/ssl.key:/etc/ssl/private/ssl.key:ro
      # - ./certs/ssl.cert:/etc/ssl/certs/ssl.cert:ro

volumes:
  n8n_data:
    driver: local