version: "3"
services:
  squid-alpine-ssl:
    image: alatas/squid-alpine-ssl:r3
    environment:
      - CN=m0nekyDev.local
      - O=m0nekyDev
      - OU=m0nekyDev
      - C=US
    ports:
      - "3128:3128"
      - "4128:4128"
    volumes:
      - ./log:/var/log/
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./cache:/var/cache
      - ./cert:/etc/squid-cert
    restart: always